---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7
    attributes:
      hello_web:
        package: httpd
        service: httpd
        docroot: /var/www/html
    verifier:
      attributes:
        package: httpd
        service: httpd

suites:
  - name: default
    run_list:
      - recipe[hello_web::default]
    verifier:
      inspec_tests:
        - test/integration/default
