script_path = "../../scripts"

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.5"
  config.vm.network "forwarded_port", guest: 80, host: 8082

  # Provisioning
  config.vm.provision "chef_zero" do |chef|
    chef.add_recipe "hello_web"
    chef.cookbooks_path = "#{script_path}/cookbooks"
    chef.nodes_path = "nodes"

    chef.json = {
      "hello_web" => {
        "package" => "httpd",
        "service" => "httpd",
        "docroot" => "/var/www/html"
      }
    }
  end
end
