script_path = "../../scripts"

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.network "forwarded_port", guest: 80, host: 8082

  # Provisioning
  config.vm.provision "chef_zero" do |chef|
    chef.add_recipe "hello_web"
    chef.cookbooks_path = "#{script_path}/cookbooks"
    chef.nodes_path = "nodes"
  end
end
