---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: all
  require_ansible_repo: false
  require_ansible_omnibus: true
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbose: false
  ansible_diff: true
  roles_path: ..

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
