---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: all
  require_ansible_repo: false
  require_ansible_omnibus: true
  # require_chef_for_busser: false
  # require_ruby_for_busser: false
  ansible_verbose: false
  ansible_diff: true
  roles_path: ..

# verifier:
#   name: inspec

verifier:
  name: shell
  command: >
    py.test
    --host="paramiko://${KITCHEN_USERNAME}@${KITCHEN_HOSTNAME}:${KITCHEN_PORT}?ssh_identity_file=${KITCHEN_SSH_KEY}"
    "test/integration/${KITCHEN_SUITE}"

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
